
OPENCV_VERSION="4.4.0"
OPENCVSHARP_VERSION="4.4.0.20200725"
OPENVINO_VERSION="2020.4.287"

VERSION_INC=1
BASE_IMAGE="nrandell/openvino-dotnet-core-runtime"
ASPNET_IMAGE="nrandell/openvino-aspnet"
X64_VERSION="${OPENCVSHARP_VERSION}-${OPENVINO_VERSION}-${VERSION_INC}"
# ARM32_VERSION="3.1.1-2019.3.334-${VERSION_INC}"
# ARM64_VERSION="3.1.1_${OPENCV_VERSION}_2019_R3.1-${VERSION_INC}"


# DLDT_VERSION_INC="0.1"
# DOTNET_VERSION="3.1.2"
# BASE_DLDT_IMAGE="nrandell/dldt-dotnet-core-runtime"
# DLDT_VERSION="2020.1"
# DLDT_ARM64_VERSION="${DOTNET_VERSION}_${DLDT_VERSION}_${DLDT_VERSION_INC}"

# VERSION="3.1.1-${VERSION_INC}"
# OPENCVSHARP_BUILD="4"
# OPENCVSHARPEXTERN_VERSION="${OPENCVSHARP_VERSION}-${OPENCVSHARP_BUILD}"
