ARG VERSION
FROM nrandell/openvino-dotnet-core-runtime:${VERSION} as native-build

ARG OPENCVSHARP_VERSION

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    unzip \
    cmake \
    wget

WORKDIR /source

RUN wget https://github.com/shimat/opencvsharp/archive/${OPENCVSHARP_VERSION}.zip && \
    unzip ${OPENCVSHARP_VERSION}.zip && \
    rm ${OPENCVSHARP_VERSION}.zip && \
    mv opencvsharp-${OPENCVSHARP_VERSION} opencvsharp 

WORKDIR /source/opencvsharp/src/OpenCvSharpExtern/
COPY ["CMakeLists.txt", "include_opencv.h", "/source/opencvsharp/src/OpenCvSharpExtern/"]

WORKDIR /build


RUN cmake \
    -D OpenCV_DIR=/install/opencv/lib/cmake/opencv4 \
    -D InferenceEngine_DIR=/install/inference-engine/build \
    -D CMAKE_INSTALL_PREFIX=/install \
    /source/opencvsharp/src

RUN make -j $(nproc)
RUN make install
